apiVersion: v1
kind: Service
metadata:
  labels:
    run: project1-service
  name: project1-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: project1-service
  sessionAffinity: None
  type: NodePort
