apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: devops@maqe.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: route53-issuer-account-key
    # Enable the HTTP01 challenge mechanism for this Issuer
    dns01:
      providers:
      - name: route53
        route53:
          region: ap-southeast-1
          hostedZoneID: dummydata
          accessKeyID: dummydata
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key